// let3.schml should return #(struct:Int) generated by the schml compiler.

//This is the boiler plate
#include <stdio.h>
#include <stdlib.h>

void* alloc_ptr;

//These are the declarations
long u20_interp_cast_code( long u19_interp_cast_clos ,long u2_val ,long u4_type1 ,long u5_type2 ,long u6_label );

//Obviously this is the main function
int main( ){
long u1_interp_cast;
long u14_prog_returns;
long u0_a;
u1_interp_cast = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)u1_interp_cast)[0] = ((long)u20_interp_cast_code);
((long*)u1_interp_cast)[1] = 0;
u14_prog_returns = (u0_a = 1, u0_a);
printf("Int : %d\n", (void *)u14_prog_returns);
return 0;
}


//Here are all the definitions for Subroutines
long u20_interp_cast_code( long u19_interp_cast_clos ,long u2_val ,long u4_type1 ,long u5_type2 ,long u6_label ){
long u7_tag;
long u8_type1;
long u9_tag1;
long u15_dyn_box;
long u10_tag2;
long u11_value;
long u17_tmp_clos;
long u12_tag1;
long u16_dyn_box;
long u13_tag2;
long u18_tmp_clos;
if (u4_type1 == 7){
if (7 == u5_type2){
return u2_val;
} else {
u7_tag = (u2_val & 7);
if (1 == u7_tag){
if (15 == u5_type2){
return (u2_val >> 3);
} else {
if (7 == u5_type2){
return (((u2_val >> 3) << 3) + 1);
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
if (7 == u7_tag){
if (23 == u5_type2){
return (u2_val >> 3);
} else {
if (7 == u5_type2){
return (((u2_val >> 3) << 3) + 7);
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
if (0 == u7_tag){
u8_type1 = ((long*)u2_val)[1];
u9_tag1 = (u8_type1 & 7);
if (0 == u9_tag1){
if (7 == u5_type2){
u15_dyn_box = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)u15_dyn_box)[0] = ((long*)u2_val)[0];
((long*)u15_dyn_box)[1] = u8_type1;
return u15_dyn_box;
} else {
u10_tag2 = (u5_type2 & 7);
if (u10_tag2 == 0){
u11_value = ((long*)u2_val)[0];
u17_tmp_clos = ((long*)u11_value)[1];
return (((long (*)(long,long,long,long,long))((long*)u17_tmp_clos)[0])(u17_tmp_clos,u11_value,u8_type1,u5_type2,u6_label));
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
if (u8_type1 == 15){
if (15 == u5_type2){
return ((long*)u2_val)[0];
} else {
if (7 == u5_type2){
return ((((long*)u2_val)[0] << 3) + 1);
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
if (u8_type1 == 23){
if (23 == u5_type2){
return ((long*)u2_val)[0];
} else {
if (7 == u5_type2){
return ((((long*)u2_val)[0] << 3) + 7);
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
}
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
}
}
} else {
u12_tag1 = (u4_type1 & 7);
if (0 == u12_tag1){
if (7 == u5_type2){
u16_dyn_box = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)u16_dyn_box)[0] = u2_val;
((long*)u16_dyn_box)[1] = u4_type1;
return u16_dyn_box;
} else {
u13_tag2 = (u5_type2 & 7);
if (u13_tag2 == 0){
u18_tmp_clos = ((long*)u2_val)[1];
return (((long (*)(long,long,long,long,long))((long*)u18_tmp_clos)[0])(u18_tmp_clos,u2_val,u4_type1,u5_type2,u6_label));
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
if (u4_type1 == 15){
if (15 == u5_type2){
return u2_val;
} else {
if (7 == u5_type2){
return ((u2_val << 3) + 1);
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
if (u4_type1 == 23){
if (23 == u5_type2){
return u2_val;
} else {
if (7 == u5_type2){
return ((u2_val << 3) + 7);
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
} else {
puts(((const char*) u6_label));
exit(-1);
return 0;
}
}
}
}
}

