// blame1.schml should return #(struct:Int) generated by the schml compiler.

//This is the boiler plate
#include <stdio.h>
#include <stdlib.h>

void* alloc_ptr;

//These are the declarations
long u17_interp_cast_code( long u16_interp_cast_clos ,long u1_val ,long u3_type1 ,long u4_type2 ,long u5_label );

//Obviously this is the main function
int main( ){
long u16_interp_cast_clos;
long u13_prog_returns;
u16_interp_cast_clos = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
 0 ;
 0 ;
u13_prog_returns = (1 + 1);
 0 ;
return 0;
}


//Here are all the definitions for Subroutines
long u17_interp_cast_code( long u16_interp_cast_clos ,long u1_val ,long u3_type1 ,long u4_type2 ,long u5_label ){
long u6_tag;
long u7_type1;
long u8_tag1;
long u19_dyn_box_init;
long u18_dyn_box_init;
long u20_dyn_box;
long u9_tag2;
long u10_value;
long u14_tmp_clos;
long u11_tag1;
long u22_dyn_box_init;
long u21_dyn_box_init;
long u23_dyn_box;
long u12_tag2;
long u15_tmp_clos;
if (u3_type1 == 7){
if (7 == u4_type2){
return u1_val;
} else {
u6_tag = ((long*)u1_val)[1];
if (1 == u6_tag){
if (15 == u4_type2){
return (u1_val >> 3);
} else {
if (7 == u4_type2){
return (((u1_val >> 3) << 3) + 1);
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
if (7 == u6_tag){
if (23 == u4_type2){
return (u1_val >> 3);
} else {
if (7 == u4_type2){
return (((u1_val >> 3) << 3) + 7);
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
if (0 == u6_tag){
u7_type1 = ((long*)u1_val)[1];
u8_tag1 = (u7_type1 & 7);
if (0 == u8_tag1){
if (7 == u4_type2){
u18_dyn_box_init = ((long*)u1_val)[0];
u19_dyn_box_init = u7_type1;
u20_dyn_box = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
 0 ;
 0 ;
return u20_dyn_box;
} else {
u9_tag2 = (u4_type2 & 7);
if (u9_tag2 == 0){
u10_value = ((long*)u1_val)[0];
u14_tmp_clos = ((long*)u10_value)[1];
return (((long (*)(long,long,long,long,long))((long*)u14_tmp_clos)[0])(u14_tmp_clos,u10_value,u7_type1,u4_type2,u5_label));
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
if (u7_type1 == 15){
if (15 == u4_type2){
return ((long*)u1_val)[0];
} else {
if (7 == u4_type2){
return ((((long*)u1_val)[0] << 3) + 1);
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
if (u7_type1 == 23){
if (23 == u4_type2){
return ((long*)u1_val)[0];
} else {
if (7 == u4_type2){
return ((((long*)u1_val)[0] << 3) + 7);
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
 0 ;
 0 ;
return 0;
}
}
}
} else {
 0 ;
 0 ;
return 0;
}
}
}
}
} else {
u11_tag1 = (u3_type1 & 7);
if (0 == u11_tag1){
if (7 == u4_type2){
u21_dyn_box_init = u1_val;
u22_dyn_box_init = u3_type1;
u23_dyn_box = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
 0 ;
 0 ;
return u23_dyn_box;
} else {
u12_tag2 = (u4_type2 & 7);
if (u12_tag2 == 0){
u15_tmp_clos = ((long*)u1_val)[1];
return (((long (*)(long,long,long,long,long))((long*)u15_tmp_clos)[0])(u15_tmp_clos,u1_val,u3_type1,u4_type2,u5_label));
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
if (u3_type1 == 15){
if (15 == u4_type2){
return u1_val;
} else {
if (7 == u4_type2){
return ((u1_val << 3) + 1);
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
if (u3_type1 == 23){
if (23 == u4_type2){
return u1_val;
} else {
if (7 == u4_type2){
return ((u1_val << 3) + 7);
} else {
 0 ;
 0 ;
return 0;
}
}
} else {
 0 ;
 0 ;
return 0;
}
}
}
}
}

