// ack-2-3-static.schml should return #(struct:Int) generated by the schml compiler.

//This is the boiler plate
#include <stdio.h>
#include <stdlib.h>

void* alloc_ptr;

//These are the declarations
long u31_interp_cast_code( long u30_interp_cast_clos ,long u11_val ,long u13_type1 ,long u14_type2 ,long u15_label );
long u37_cast_fn2_code( long u36_cast_fn2_clos ,long u4_f ,long u5_t1 ,long u6_t2 ,long u7_lbl );
long u33_annon_code( long u32_annon_clos ,long u9_v ,long u8_v );
long u35_annon_code( long u34_annon_clos );
long u39_ack_code( long u38_ack_clos ,long u2_m ,long u1_n );

//Obviously this is the main function
int main( ){
long u10_interp_cast;
long u23_prog_returns;
long u3_cast_fn2;
long u0_ack;
u10_interp_cast = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)u10_interp_cast)[0] = ((long)u31_interp_cast_code);
((long*)u10_interp_cast)[1] = 0;
u23_prog_returns = (u3_cast_fn2 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 4), alloc_ptr), (((long*)u3_cast_fn2)[3] = u10_interp_cast, ((long*)u3_cast_fn2)[2] = u3_cast_fn2, ((long*)u3_cast_fn2)[0] = ((long)u37_cast_fn2_code), ((long*)u3_cast_fn2)[1] = 0, (u0_ack = (long) (posix_memalign(&alloc_ptr, 8, 8 * 4), alloc_ptr), (((long*)u0_ack)[3] = u0_ack, ((long*)u0_ack)[2] = u3_cast_fn2, ((long*)u0_ack)[0] = ((long)u39_ack_code), ((long*)u0_ack)[1] = u3_cast_fn2, (((long (*)(long,long,long))((long*)u0_ack)[0])(u0_ack,2,3))))));
printf("Int : %d\n", (void *)u23_prog_returns);
return 0;
}


//Here are all the definitions for Subroutines
long u31_interp_cast_code( long u30_interp_cast_clos ,long u11_val ,long u13_type1 ,long u14_type2 ,long u15_label ){
long u16_tag;
long u17_type1;
long u18_tag1;
long u24_dyn_box;
long u19_tag2;
long u20_value;
long u28_tmp_clos;
long u21_tag1;
long u25_dyn_box;
long u22_tag2;
long u29_tmp_clos;
if (u13_type1 == 7){
if (7 == u14_type2){
return u11_val;
} else {
u16_tag = (u11_val & 7);
if (1 == u16_tag){
if (15 == u14_type2){
return (u11_val >> 3);
} else {
if (7 == u14_type2){
return (((u11_val >> 3) << 3) + 1);
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
if (7 == u16_tag){
if (23 == u14_type2){
return (u11_val >> 3);
} else {
if (7 == u14_type2){
return (((u11_val >> 3) << 3) + 7);
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
if (0 == u16_tag){
u17_type1 = ((long*)u11_val)[1];
u18_tag1 = (u17_type1 & 7);
if (0 == u18_tag1){
if (7 == u14_type2){
u24_dyn_box = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)u24_dyn_box)[0] = ((long*)u11_val)[0];
((long*)u24_dyn_box)[1] = u17_type1;
return u24_dyn_box;
} else {
u19_tag2 = (u14_type2 & 7);
if (u19_tag2 == 0){
u20_value = ((long*)u11_val)[0];
u28_tmp_clos = ((long*)u20_value)[1];
return (((long (*)(long,long,long,long,long))((long*)u28_tmp_clos)[0])(u28_tmp_clos,u20_value,u17_type1,u14_type2,u15_label));
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
if (u17_type1 == 15){
if (15 == u14_type2){
return ((long*)u11_val)[0];
} else {
if (7 == u14_type2){
return ((((long*)u11_val)[0] << 3) + 1);
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
if (u17_type1 == 23){
if (23 == u14_type2){
return ((long*)u11_val)[0];
} else {
if (7 == u14_type2){
return ((((long*)u11_val)[0] << 3) + 7);
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
}
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
}
}
} else {
u21_tag1 = (u13_type1 & 7);
if (0 == u21_tag1){
if (7 == u14_type2){
u25_dyn_box = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)u25_dyn_box)[0] = u11_val;
((long*)u25_dyn_box)[1] = u13_type1;
return u25_dyn_box;
} else {
u22_tag2 = (u14_type2 & 7);
if (u22_tag2 == 0){
u29_tmp_clos = ((long*)u11_val)[1];
return (((long (*)(long,long,long,long,long))((long*)u29_tmp_clos)[0])(u29_tmp_clos,u11_val,u13_type1,u14_type2,u15_label));
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
if (u13_type1 == 15){
if (15 == u14_type2){
return u11_val;
} else {
if (7 == u14_type2){
return ((u11_val << 3) + 1);
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
if (u13_type1 == 23){
if (23 == u14_type2){
return u11_val;
} else {
if (7 == u14_type2){
return ((u11_val << 3) + 7);
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
} else {
puts(((const char*) u15_label));
exit(-1);
return 0;
}
}
}
}
}

long u37_cast_fn2_code( long u36_cast_fn2_clos ,long u4_f ,long u5_t1 ,long u6_t2 ,long u7_lbl ){
long u26_annon;
long u27_annon;
if (((long*)u5_t1)[0] == ((long*)u6_t2)[0]){
u26_annon = (long) (posix_memalign(&alloc_ptr, 8, 8 * 8), alloc_ptr);
((long*)u26_annon)[7] = u4_f;
((long*)u26_annon)[6] = u6_t2;
((long*)u26_annon)[5] = u5_t1;
((long*)u26_annon)[4] = u7_lbl;
((long*)u26_annon)[3] = ((long*)u36_cast_fn2_clos)[3];
((long*)u26_annon)[2] = ((long*)u36_cast_fn2_clos)[2];
((long*)u26_annon)[0] = ((long)u33_annon_code);
((long*)u26_annon)[1] = ((long*)u36_cast_fn2_clos)[2];
return u26_annon;
} else {
u27_annon = (long) (posix_memalign(&alloc_ptr, 8, 8 * 4), alloc_ptr);
((long*)u27_annon)[3] = u7_lbl;
((long*)u27_annon)[2] = ((long*)u36_cast_fn2_clos)[2];
((long*)u27_annon)[0] = ((long)u35_annon_code);
((long*)u27_annon)[1] = ((long*)u36_cast_fn2_clos)[2];
return u27_annon;
}
}

long u33_annon_code( long u32_annon_clos ,long u9_v ,long u8_v ){
return (((long (*)(long,long,long,long,long))((long*)((long*)u32_annon_clos)[3])[0])(((long*)u32_annon_clos)[3],(((long (*)(long,long,long))((long*)((long*)u32_annon_clos)[7])[0])(((long*)u32_annon_clos)[7],(((long (*)(long,long,long,long,long))((long*)((long*)u32_annon_clos)[3])[0])(((long*)u32_annon_clos)[3],u9_v,((long*)((long*)u32_annon_clos)[6])[2],((long*)((long*)u32_annon_clos)[5])[2],((long*)u32_annon_clos)[4])),(((long (*)(long,long,long,long,long))((long*)((long*)u32_annon_clos)[3])[0])(((long*)u32_annon_clos)[3],u8_v,((long*)((long*)u32_annon_clos)[6])[3],((long*)((long*)u32_annon_clos)[5])[3],((long*)u32_annon_clos)[4])))),((long*)((long*)u32_annon_clos)[5])[1],((long*)((long*)u32_annon_clos)[6])[1],((long*)u32_annon_clos)[4]));
}

long u35_annon_code( long u34_annon_clos ){
puts(((const char*) ((long*)u34_annon_clos)[3]));
exit(-1);
return 0;
}

long u39_ack_code( long u38_ack_clos ,long u2_m ,long u1_n ){
if (u2_m == 0){
return (u1_n + 1);
} else {
if (u1_n == 0){
return (((long (*)(long,long,long))((long*)((long*)u38_ack_clos)[3])[0])(((long*)u38_ack_clos)[3],(u2_m - 1),1));
} else {
return (((long (*)(long,long,long))((long*)((long*)u38_ack_clos)[3])[0])(((long*)u38_ack_clos)[3],(u2_m - 1),(((long (*)(long,long,long))((long*)((long*)u38_ack_clos)[3])[0])(((long*)u38_ack_clos)[3],u2_m,(u1_n - 1)))));
}
}
}

