// ack-2-3-static.schml should return #(struct:Int) generated by the schml compiler.

//This is the boiler plate
#include <stdio.h>
#include <stdlib.h>

void* alloc_ptr;

//These are the declarations
long interp_cast_code31( long interp_cast_clos30 ,long val11 ,long type113 ,long type214 ,long label15 );
long cast_fn2_code37( long cast_fn2_clos36 ,long f4 ,long t15 ,long t26 ,long lbl7 );
long annon_code33( long annon_clos32 ,long v9 ,long v8 );
long annon_code35( long annon_clos34 );
long ack_code39( long ack_clos38 ,long m2 ,long n1 );

//Obviously this is the main function
int main( ){
long interp_cast10;
long prog_returns23;
long cast_fn23;
long ack0;
interp_cast10 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)interp_cast10)[0] = ((long)interp_cast_code31);
((long*)interp_cast10)[1] = 0;
prog_returns23 = (cast_fn23 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 4), alloc_ptr), (((long*)cast_fn23)[3] = interp_cast10, ((long*)cast_fn23)[2] = cast_fn23, ((long*)cast_fn23)[0] = ((long)cast_fn2_code37), ((long*)cast_fn23)[1] = 0, (ack0 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 4), alloc_ptr), (((long*)ack0)[3] = ack0, ((long*)ack0)[2] = cast_fn23, ((long*)ack0)[0] = ((long)ack_code39), ((long*)ack0)[1] = cast_fn23, (((long (*)(long,long,long))((long*)ack0)[0])(ack0,2,3))))));
printf("Int : %d\n", (void *)prog_returns23);
return 0;
}


//Here are all the definitions for Subroutines
long interp_cast_code31( long interp_cast_clos30 ,long val11 ,long type113 ,long type214 ,long label15 ){
long tag16;
long type117;
long tag118;
long dyn_box24;
long tag219;
long value20;
long tmp_clos28;
long tag121;
long dyn_box25;
long tag222;
long tmp_clos29;
if (type113 == 7){
if (7 == type214){
return val11;
} else {
tag16 = (val11 & 7);
if (1 == tag16){
if (15 == type214){
return (val11 >> 3);
} else {
if (7 == type214){
return (((val11 >> 3) << 3) + 1);
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
if (7 == tag16){
if (23 == type214){
return (val11 >> 3);
} else {
if (7 == type214){
return (((val11 >> 3) << 3) + 7);
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
if (0 == tag16){
type117 = ((long*)val11)[1];
tag118 = (type117 & 7);
if (0 == tag118){
if (7 == type214){
dyn_box24 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)dyn_box24)[0] = ((long*)val11)[0];
((long*)dyn_box24)[1] = type117;
return dyn_box24;
} else {
tag219 = (type214 & 7);
if (tag219 == 0){
value20 = ((long*)val11)[0];
tmp_clos28 = ((long*)value20)[1];
return (((long (*)(long,long,long,long,long))((long*)tmp_clos28)[0])(tmp_clos28,value20,type117,type214,label15));
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
if (type117 == 15){
if (15 == type214){
return ((long*)val11)[0];
} else {
if (7 == type214){
return ((((long*)val11)[0] << 3) + 1);
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
if (type117 == 23){
if (23 == type214){
return ((long*)val11)[0];
} else {
if (7 == type214){
return ((((long*)val11)[0] << 3) + 7);
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
}
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
}
}
} else {
tag121 = (type113 & 7);
if (0 == tag121){
if (7 == type214){
dyn_box25 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 2), alloc_ptr);
((long*)dyn_box25)[0] = val11;
((long*)dyn_box25)[1] = type113;
return dyn_box25;
} else {
tag222 = (type214 & 7);
if (tag222 == 0){
tmp_clos29 = ((long*)val11)[1];
return (((long (*)(long,long,long,long,long))((long*)tmp_clos29)[0])(tmp_clos29,val11,type113,type214,label15));
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
if (type113 == 15){
if (15 == type214){
return val11;
} else {
if (7 == type214){
return ((val11 << 3) + 1);
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
if (type113 == 23){
if (23 == type214){
return val11;
} else {
if (7 == type214){
return ((val11 << 3) + 7);
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
} else {
puts(((const char*) label15));
exit(-1);
return 0;
}
}
}
}
}

long cast_fn2_code37( long cast_fn2_clos36 ,long f4 ,long t15 ,long t26 ,long lbl7 ){
long annon26;
long annon27;
if (((long*)t15)[0] == ((long*)t26)[0]){
annon26 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 8), alloc_ptr);
((long*)annon26)[7] = f4;
((long*)annon26)[6] = t26;
((long*)annon26)[5] = t15;
((long*)annon26)[4] = lbl7;
((long*)annon26)[3] = ((long*)cast_fn2_clos36)[3];
((long*)annon26)[2] = ((long*)cast_fn2_clos36)[2];
((long*)annon26)[0] = ((long)annon_code33);
((long*)annon26)[1] = ((long*)cast_fn2_clos36)[2];
return annon26;
} else {
annon27 = (long) (posix_memalign(&alloc_ptr, 8, 8 * 4), alloc_ptr);
((long*)annon27)[3] = lbl7;
((long*)annon27)[2] = ((long*)cast_fn2_clos36)[2];
((long*)annon27)[0] = ((long)annon_code35);
((long*)annon27)[1] = ((long*)cast_fn2_clos36)[2];
return annon27;
}
}

long annon_code33( long annon_clos32 ,long v9 ,long v8 ){
return (((long (*)(long,long,long,long,long))((long*)((long*)annon_clos32)[3])[0])(((long*)annon_clos32)[3],(((long (*)(long,long,long))((long*)((long*)annon_clos32)[7])[0])(((long*)annon_clos32)[7],(((long (*)(long,long,long,long,long))((long*)((long*)annon_clos32)[3])[0])(((long*)annon_clos32)[3],v9,((long*)((long*)annon_clos32)[6])[2],((long*)((long*)annon_clos32)[5])[2],((long*)annon_clos32)[4])),(((long (*)(long,long,long,long,long))((long*)((long*)annon_clos32)[3])[0])(((long*)annon_clos32)[3],v8,((long*)((long*)annon_clos32)[6])[3],((long*)((long*)annon_clos32)[5])[3],((long*)annon_clos32)[4])))),((long*)((long*)annon_clos32)[5])[1],((long*)((long*)annon_clos32)[6])[1],((long*)annon_clos32)[4]));
}

long annon_code35( long annon_clos34 ){
puts(((const char*) ((long*)annon_clos34)[3]));
exit(-1);
return 0;
}

long ack_code39( long ack_clos38 ,long m2 ,long n1 ){
if (m2 == 0){
return (n1 + 1);
} else {
if (n1 == 0){
return (((long (*)(long,long,long))((long*)((long*)ack_clos38)[3])[0])(((long*)ack_clos38)[3],(m2 - 1),1));
} else {
return (((long (*)(long,long,long))((long*)((long*)ack_clos38)[3])[0])(((long*)ack_clos38)[3],(m2 - 1),(((long (*)(long,long,long))((long*)((long*)ack_clos38)[3])[0])(((long*)ack_clos38)[3],m2,(n1 - 1)))));
}
}
}

